name: skinet-reverse-proxy

run-name: skinet-reverse-proxy 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is a job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: get sources
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build the Docker image
        working-directory: ${{ github.workspace }}
        run: docker build . -t altair961/skinet-reverse-proxy:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the images to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/skinet-reverse-proxy
  # This is a job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
          docker rmi images | grep ${{ secrets.DOCKERHUB_USERNAME }}/skinet-reverse-proxy
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/skinet-reverse-proxy:latest
            docker stop skinet-reverse-proxy || true
            docker rm skinet-reverse-proxy || true
            docker run -d -p 8080:80 --name skinet-reverse-proxy ${{ secrets.DOCKERHUB_USERNAME }}/skinet-reverse-proxy:latest